apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: ivolve
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30012
